version: '3.4'

services:
  elasticsearch:
    image: elasticsearch:8.2.2
  
  logstash:
    image: logstash:8.2.2
  
  kibana:
    image: kibana:8.2.2
  
  psql:
    image: postgres:latest
  
  mongo:
    image: mongo:latest
  
  redis:
    image: redis:alpine
